// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod exports {
    pub mod sprawl {
        pub mod stack_detector {
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod detector {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                #[derive(Clone)]
                pub struct Dependency {
                    pub name: _rt::String,
                    pub version_spec: _rt::String,
                    pub is_local_path: bool,
                }
                impl ::core::fmt::Debug for Dependency {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("Dependency")
                            .field("name", &self.name)
                            .field("version-spec", &self.version_spec)
                            .field("is-local-path", &self.is_local_path)
                            .finish()
                    }
                }
                #[derive(Clone)]
                pub struct ReproducibilityVerdict {
                    pub is_reproducible: bool,
                    pub evidence: _rt::Vec<_rt::String>,
                }
                impl ::core::fmt::Debug for ReproducibilityVerdict {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("ReproducibilityVerdict")
                            .field("is-reproducible", &self.is_reproducible)
                            .field("evidence", &self.evidence)
                            .finish()
                    }
                }
                #[derive(Clone)]
                pub struct StackInfo {
                    pub ecosystem: _rt::String,
                    pub entry_points: _rt::Vec<_rt::String>,
                    pub dependencies: _rt::Vec<Dependency>,
                    pub reproducibility: ReproducibilityVerdict,
                }
                impl ::core::fmt::Debug for StackInfo {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("StackInfo")
                            .field("ecosystem", &self.ecosystem)
                            .field("entry-points", &self.entry_points)
                            .field("dependencies", &self.dependencies)
                            .field("reproducibility", &self.reproducibility)
                            .finish()
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_detect_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                    let result1 = T::detect(_rt::string_lift(bytes0));
                    let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result1 {
                        Some(e) => {
                            *ptr2.add(0).cast::<u8>() = (1i32) as u8;
                            let StackInfo {
                                ecosystem: ecosystem3,
                                entry_points: entry_points3,
                                dependencies: dependencies3,
                                reproducibility: reproducibility3,
                            } = e;
                            let vec4 = (ecosystem3.into_bytes()).into_boxed_slice();
                            let ptr4 = vec4.as_ptr().cast::<u8>();
                            let len4 = vec4.len();
                            ::core::mem::forget(vec4);
                            *ptr2
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len4;
                            *ptr2
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr4.cast_mut();
                            let vec6 = entry_points3;
                            let len6 = vec6.len();
                            let layout6 = _rt::alloc::Layout::from_size_align_unchecked(
                                vec6.len() * (2 * ::core::mem::size_of::<*const u8>()),
                                ::core::mem::size_of::<*const u8>(),
                            );
                            let result6 = if layout6.size() != 0 {
                                let ptr = _rt::alloc::alloc(layout6).cast::<u8>();
                                if ptr.is_null() {
                                    _rt::alloc::handle_alloc_error(layout6);
                                }
                                ptr
                            } else {
                                ::core::ptr::null_mut()
                            };
                            for (i, e) in vec6.into_iter().enumerate() {
                                let base = result6
                                    .add(i * (2 * ::core::mem::size_of::<*const u8>()));
                                {
                                    let vec5 = (e.into_bytes()).into_boxed_slice();
                                    let ptr5 = vec5.as_ptr().cast::<u8>();
                                    let len5 = vec5.len();
                                    ::core::mem::forget(vec5);
                                    *base
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len5;
                                    *base.add(0).cast::<*mut u8>() = ptr5.cast_mut();
                                }
                            }
                            *ptr2
                                .add(4 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len6;
                            *ptr2
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = result6;
                            let vec10 = dependencies3;
                            let len10 = vec10.len();
                            let layout10 = _rt::alloc::Layout::from_size_align_unchecked(
                                vec10.len() * (5 * ::core::mem::size_of::<*const u8>()),
                                ::core::mem::size_of::<*const u8>(),
                            );
                            let result10 = if layout10.size() != 0 {
                                let ptr = _rt::alloc::alloc(layout10).cast::<u8>();
                                if ptr.is_null() {
                                    _rt::alloc::handle_alloc_error(layout10);
                                }
                                ptr
                            } else {
                                ::core::ptr::null_mut()
                            };
                            for (i, e) in vec10.into_iter().enumerate() {
                                let base = result10
                                    .add(i * (5 * ::core::mem::size_of::<*const u8>()));
                                {
                                    let Dependency {
                                        name: name7,
                                        version_spec: version_spec7,
                                        is_local_path: is_local_path7,
                                    } = e;
                                    let vec8 = (name7.into_bytes()).into_boxed_slice();
                                    let ptr8 = vec8.as_ptr().cast::<u8>();
                                    let len8 = vec8.len();
                                    ::core::mem::forget(vec8);
                                    *base
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len8;
                                    *base.add(0).cast::<*mut u8>() = ptr8.cast_mut();
                                    let vec9 = (version_spec7.into_bytes()).into_boxed_slice();
                                    let ptr9 = vec9.as_ptr().cast::<u8>();
                                    let len9 = vec9.len();
                                    ::core::mem::forget(vec9);
                                    *base
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len9;
                                    *base
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>() = ptr9.cast_mut();
                                    *base
                                        .add(4 * ::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (match is_local_path7 {
                                        true => 1,
                                        false => 0,
                                    }) as u8;
                                }
                            }
                            *ptr2
                                .add(6 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len10;
                            *ptr2
                                .add(5 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = result10;
                            let ReproducibilityVerdict {
                                is_reproducible: is_reproducible11,
                                evidence: evidence11,
                            } = reproducibility3;
                            *ptr2
                                .add(7 * ::core::mem::size_of::<*const u8>())
                                .cast::<u8>() = (match is_reproducible11 {
                                true => 1,
                                false => 0,
                            }) as u8;
                            let vec13 = evidence11;
                            let len13 = vec13.len();
                            let layout13 = _rt::alloc::Layout::from_size_align_unchecked(
                                vec13.len() * (2 * ::core::mem::size_of::<*const u8>()),
                                ::core::mem::size_of::<*const u8>(),
                            );
                            let result13 = if layout13.size() != 0 {
                                let ptr = _rt::alloc::alloc(layout13).cast::<u8>();
                                if ptr.is_null() {
                                    _rt::alloc::handle_alloc_error(layout13);
                                }
                                ptr
                            } else {
                                ::core::ptr::null_mut()
                            };
                            for (i, e) in vec13.into_iter().enumerate() {
                                let base = result13
                                    .add(i * (2 * ::core::mem::size_of::<*const u8>()));
                                {
                                    let vec12 = (e.into_bytes()).into_boxed_slice();
                                    let ptr12 = vec12.as_ptr().cast::<u8>();
                                    let len12 = vec12.len();
                                    ::core::mem::forget(vec12);
                                    *base
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len12;
                                    *base.add(0).cast::<*mut u8>() = ptr12.cast_mut();
                                }
                            }
                            *ptr2
                                .add(9 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len13;
                            *ptr2
                                .add(8 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = result13;
                        }
                        None => {
                            *ptr2.add(0).cast::<u8>() = (0i32) as u8;
                        }
                    };
                    ptr2
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_detect<T: Guest>(arg0: *mut u8) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {}
                        _ => {
                            let l1 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l2 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l1, l2, 1);
                            let l3 = *arg0
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l4 = *arg0
                                .add(4 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let base7 = l3;
                            let len7 = l4;
                            for i in 0..len7 {
                                let base = base7
                                    .add(i * (2 * ::core::mem::size_of::<*const u8>()));
                                {
                                    let l5 = *base.add(0).cast::<*mut u8>();
                                    let l6 = *base
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    _rt::cabi_dealloc(l5, l6, 1);
                                }
                            }
                            _rt::cabi_dealloc(
                                base7,
                                len7 * (2 * ::core::mem::size_of::<*const u8>()),
                                ::core::mem::size_of::<*const u8>(),
                            );
                            let l8 = *arg0
                                .add(5 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l9 = *arg0
                                .add(6 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let base14 = l8;
                            let len14 = l9;
                            for i in 0..len14 {
                                let base = base14
                                    .add(i * (5 * ::core::mem::size_of::<*const u8>()));
                                {
                                    let l10 = *base.add(0).cast::<*mut u8>();
                                    let l11 = *base
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    _rt::cabi_dealloc(l10, l11, 1);
                                    let l12 = *base
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l13 = *base
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    _rt::cabi_dealloc(l12, l13, 1);
                                }
                            }
                            _rt::cabi_dealloc(
                                base14,
                                len14 * (5 * ::core::mem::size_of::<*const u8>()),
                                ::core::mem::size_of::<*const u8>(),
                            );
                            let l15 = *arg0
                                .add(8 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l16 = *arg0
                                .add(9 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let base19 = l15;
                            let len19 = l16;
                            for i in 0..len19 {
                                let base = base19
                                    .add(i * (2 * ::core::mem::size_of::<*const u8>()));
                                {
                                    let l17 = *base.add(0).cast::<*mut u8>();
                                    let l18 = *base
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    _rt::cabi_dealloc(l17, l18, 1);
                                }
                            }
                            _rt::cabi_dealloc(
                                base19,
                                len19 * (2 * ::core::mem::size_of::<*const u8>()),
                                ::core::mem::size_of::<*const u8>(),
                            );
                        }
                    }
                }
                pub trait Guest {
                    fn detect(project_root: _rt::String) -> Option<StackInfo>;
                }
                #[doc(hidden)]
                macro_rules! __export_sprawl_stack_detector_detector_1_0_0_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "sprawl:stack-detector/detector@1.0.0#detect")] unsafe extern "C"
                        fn export_detect(arg0 : * mut u8, arg1 : usize,) -> * mut u8 {
                        unsafe { $($path_to_types)*:: _export_detect_cabi::<$ty > (arg0,
                        arg1) } } #[unsafe (export_name =
                        "cabi_post_sprawl:stack-detector/detector@1.0.0#detect")] unsafe
                        extern "C" fn _post_return_detect(arg0 : * mut u8,) { unsafe {
                        $($path_to_types)*:: __post_return_detect::<$ty > (arg0) } } };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_sprawl_stack_detector_detector_1_0_0_cabi;
                #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                struct _RetArea(
                    [::core::mem::MaybeUninit<
                        u8,
                    >; 10 * ::core::mem::size_of::<*const u8>()],
                );
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 10
                        * ::core::mem::size_of::<*const u8>()],
                );
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    pub use alloc_crate::string::String;
    pub use alloc_crate::vec::Vec;
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            String::from_utf8_unchecked(bytes)
        }
    }
    pub use alloc_crate::alloc;
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr, layout);
    }
    extern crate alloc as alloc_crate;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_stack_detector_plugin_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*::
        exports::sprawl::stack_detector::detector::__export_sprawl_stack_detector_detector_1_0_0_cabi!($ty
        with_types_in $($path_to_types_root)*::
        exports::sprawl::stack_detector::detector);
    };
}
#[doc(inline)]
pub(crate) use __export_stack_detector_plugin_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:sprawl:stack-detector@1.0.0:stack-detector-plugin:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 471] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xcb\x02\x01A\x02\x01\
A\x02\x01B\x0b\x01r\x03\x04names\x0cversion-specs\x0dis-local-path\x7f\x04\0\x0a\
dependency\x03\0\0\x01ps\x01r\x02\x0fis-reproducible\x7f\x08evidence\x02\x04\0\x17\
reproducibility-verdict\x03\0\x03\x01p\x01\x01r\x04\x09ecosystems\x0centry-point\
s\x02\x0cdependencies\x05\x0freproducibility\x04\x04\0\x0astack-info\x03\0\x06\x01\
k\x07\x01@\x01\x0cproject-roots\0\x08\x04\0\x06detect\x01\x09\x04\0$sprawl:stack\
-detector/detector@1.0.0\x05\0\x04\01sprawl:stack-detector/stack-detector-plugin\
@1.0.0\x04\0\x0b\x1b\x01\0\x15stack-detector-plugin\x03\0\0\0G\x09producers\x01\x0c\
processed-by\x02\x0dwit-component\x070.227.1\x10wit-bindgen-rust\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
