use clap::Args;
use sprawl_core::platform::sprawl_data_dir;
use sprawl_core::Result;
use std::fs;
use std::io::Write;
use std::path::PathBuf;
use which::which;

#[derive(Args)]
pub struct ProfileMachineArgs {}

pub fn handle(_args: &ProfileMachineArgs, is_json: bool) -> Result<()> {
    let mut persona = "Polyglot"; // default
    let mut detected_tools = Vec::new();

    // Scan PATH for common binaries to infer persona
    let is_rust = which("cargo").is_ok() || which("rustc").is_ok();
    let is_node = which("node").is_ok() || which("npm").is_ok() || which("yarn").is_ok();
    let is_python = which("python").is_ok() || which("python3").is_ok() || which("pip").is_ok();

    if is_rust {
        detected_tools.push("cargo");
        detected_tools.push("rustc");
    }
    if is_node {
        detected_tools.push("node");
        detected_tools.push("npm");
    }
    if is_python {
        detected_tools.push("python");
    }

    if is_rust && !is_node && !is_python {
        persona = "Rustacean";
    } else if is_node && !is_rust && !is_python {
        persona = "Web Developer";
    } else if is_python && !is_rust && !is_node {
        persona = "Data Scientist";
    } else if is_rust || is_node || is_python {
        persona = "Full Stack Engineer";
    }

    if !is_json {
        println!("🔍 Profiling machine...");
        if !detected_tools.is_empty() {
            println!("🛠️  Detected tools in PATH: {}", detected_tools.join(", "));
        }
        println!("👤 Inferred Persona: {}", persona);
    }

    let config_dir = sprawl_data_dir().unwrap_or_else(|_| {
        let home = std::env::var("HOME").unwrap_or_else(|_| ".".into());
        PathBuf::from(home).join(".sprawl")
    }).join("config");

    if !config_dir.exists() {
        fs::create_dir_all(&config_dir).unwrap_or_default();
    }

    // Write a patterns.toml
    let patterns_path = config_dir.join("patterns.toml");
    let mut patterns_content = String::from(
        "# Sprawl Global Patterns\n\
        # Auto-generated by profile-machine\n\n\
        [ignore]\n",
    );

    patterns_content.push_str("directories = [\"node_modules\", \"target\", \"dist\", \"build\", \".venv\", \"venv\", \"__pycache__\"]\n");
    patterns_content.push_str("extensions = [\"pyc\", \"o\", \"so\", \"dll\", \"exe\", \"log\", \"tmp\"]\n");

    if let Ok(mut file) = fs::File::create(&patterns_path) {
        let _ = file.write_all(patterns_content.as_bytes());
        if !is_json {
            println!("💾 Generated patterns configuration at: {}", patterns_path.display());
        }
    }

    if is_json {
        println!("{}", serde_json::json!({
            "persona": persona,
            "detected_tools": detected_tools,
            "patterns_file": patterns_path.display().to_string(),
            "is_rust": is_rust,
            "is_node": is_node,
            "is_python": is_python
        }));
    }

    Ok(())
}
